### ISSUE TITLE
does not watch recursively

### ISSUE THREAD

**Issue by mheese** [dc0d/dirwatch#1]
Followint the example from the docs: at least under Linux it does not watch recursively for changes, only direct folder changes trigger events.

**Comment by dc0d** [comment]
@mheese Would you please share a github gist?

The tests are passed on Ubuntu 18.04.

**Comment by mheese** [comment]
hey, I can try to reproduce the code that I had ... but for now I switched to another project where it worked out of the box

**Comment by dc0d** [comment]
@mheese I have hit that case but I can not reproduce it. So I have simplified the API to one function `Add()` and removed adding directories from the constructor.

Would you please retry your case with new API? (That would be awesome! Thanks in advance!)
